trigger:
- master

jobs:

# Run a build on Linux
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      make

# Run a build on macOS at the same time
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - script: |
      make
